matrix:
  fast_finish: true

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VCVARSALL: C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat
      PLATFORM: x64
      CC: cl.exe
      CXX: cl.exe

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VCVARSALL: C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat
      PLATFORM: x86
      CC: clang-cl.exe
      CXX: clang-cl.exe
      # https://gitlab.kitware.com/cmake/cmake/issues/16259.
      CFLAGS: -m32
      CXXFLAGS: -m32

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VCVARSALL: C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      PLATFORM: x86
      CC: cl.exe
      CXX: cl.exe

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VCVARSALL: C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      PLATFORM: x64
      CC: clang-cl.exe
      CXX: clang-cl.exe
      CFLAGS: -m64
      CXXFLAGS: -m64

install:
    # LLVM's (clang-cl) MSBuild integration is outdated so we use Ninja instead.
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: scoop install ninja

before_build:
  # Set MSVC's enviroment variables.
  - call %VCVARSALL% %PLATFORM%
  - mkdir build
  - cd build
  # Build reproc as a shared library so CI verifies all the necessary symbols
  # are exported from the dll's.
  - cmake ..
      -G Ninja
      -DCMAKE_BUILD_TYPE=Debug
      -DBUILD_SHARED_LIBS=ON
      -DREPROC++=ON
      -DREPROC_TESTS=ON
      -DREPROC_EXAMPLES=ON
      -DREPROC_CI=ON
      -DREPROC_TIDY=ON

build_script: cmake --build .

before_test:
  # Make sure the tests and examples can find the reproc and reproc++ dll's.
  - set PATH=%APPVEYOR_BUILD_FOLDER%/build/reproc/lib;%PATH%
  - set PATH=%APPVEYOR_BUILD_FOLDER%/build/reproc++/lib;%PATH%

test_script:
  - cmake --build . --target reproc-run-tests
  # Make sure the examples don't crash or return a non-zero exit code.
  - .\reproc\examples\git-status >NUL
  - .\reproc++\examples\\cmake-help >NUL
