platform:
  - x86
  - x64

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VCVARSALL: C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat

install:
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: scoop install ninja

before_build:
  - call %VCVARSALL% %PLATFORM%
  - cmake .
      -G Ninja
      -DCMAKE_BUILD_TYPE=Debug
      -DBUILD_SHARED_LIBS=ON
      -DREPROC_BUILD_TESTS=ON
      -DREPROC_BUILD_EXAMPLES=ON
      -DREPROC_BUILD_CXX_WRAPPER=ON
      -DREPROC_CI=ON
      -DREPROC_TIDY=ON
      -DREPROC_INSTALL=ON
      -DREPROC_FORMAT=ON
      -DREPROC_ENABLE_W4=ON

build_script: cmake --build .

test_script: cmake --build . --target reproc-run-tests

