version: "{build}"
image: Visual Studio 2017
platform: x64
configuration: Debug

environment:
  CLICOLOR_FORCE: 1
  matrix:
    - MSYSTEM: MINGW64
    - MSYSTEM: MSVC

before_build:
  - cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DPROCESS_LIB_BUILD_TESTS=ON
    -DPROCESS_LIB_BUILD_EXAMPLES=ON -DPROCESS_LIB_BUILD_CPP_WRAPPER=ON
    -DPROCESS_LIB_CI=ON -DPROCESS_LIB_RUN_CLANG_TIDY=ON .

build:
  project: process-lib.sln

test_script:
  - .\test\Debug\tests.exe
