version: "{build}"
image: Visual Studio 2017
platform: x64
configuration: Debug

install:
  - git submodule update --init --recursive

environment:
  CLICOLOR_FORCE: 1
  matrix:
    - MSYSTEM: MINGW64
    - MSYSTEM: MSVC

before_build: 
  - cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DPROCESS_LIB_BUILD_TESTS=ON .

build:
  project: process-lib.sln

test_script:
  - .\test\Debug\tests.exe
