version: "{build}"
image: Visual Studio 2017
platform: x64
configuration: Debug

environment:
  # Add directory of dll to PATH so Windows can find it
  PATH: $(APPVEYOR_BUILD_FOLDER)\lib\Debug;$(PATH)
  CLICOLOR_FORCE: 1
  matrix:
    - MSYSTEM: MINGW64
    - MSYSTEM: MSVC

before_build:
  - cmake .
      -DREPROC_BUILD_TESTS=ON
      -DREPROC_BUILD_EXAMPLES=ON
      -DREPROC_BUILD_CXX_WRAPPER=ON
      -DREPROC_CI=ON
      -DREPROC_TIDY=ON
      -DREPROC_INSTALL=ON
      -DREPROC_FORMAT=ON
      -DCMAKE_GENERATOR_PLATFORM=x64
      -DBUILD_SHARED_LIBS=ON

build:
  project: reproc.sln

test_script: cmake --build . --target reproc-run-tests
