version: "{build}"
image: Visual Studio 2017
platform: x64
configuration: Debug

environment:
  CLICOLOR_FORCE: 1
  matrix:
    - MSYSTEM: MINGW64
    - MSYSTEM: MSVC

before_build:
  - cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DREPROC_BUILD_TESTS=ON
    -DREPROC_BUILD_EXAMPLES=ON -DREPROC_BUILD_CPP_WRAPPER=ON
    -DREPROC_CI=ON -DREPROC_RUN_CLANG_TIDY=ON -DBUILD_SHARED_LIBS=ON .

build:
  project: reproc.sln

test_script:
  - .\test\Debug\tests.exe
