parameters:
  name: ''
  image: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.image }}
  steps:
  # brew upgrade returns a non-zero error code if the package is already
  # up-to-date. To avoid this we check if the package is out-of-date first.
  - script: |
      if (brew outdated | grep -q cmake); then
        brew upgrade cmake;
      fi
    displayName: Install

  - script: |
      cmake \
        -B $(Build.SourcesDirectory)/build \
        -S $(Build.SourcesDirectory) \
        -DCMAKE_BUILD_TYPE=Debug \
        -DBUILD_SHARED_LIBS=ON \
        -DREPROC++=ON \
        -DREPROC_TEST=ON \
        -DREPROC_EXAMPLES=ON \
        -DREPROC_WARNINGS_AS_ERRORS=ON \
        -DREPROC_SANITIZERS=ON
    displayName: Configure

  - script: cmake --build $(Build.SourcesDirectory)/build --parallel 2
    displayName: Build

  - script: |
      build/test
      build/reproc/examples/drain > /dev/null
      build/reproc/examples/git-status > /dev/null
      build/reproc++/examples/background cmake --help > /dev/null
      build/reproc++/examples/cmake-help > /dev/null
      build/reproc++/examples/forward cmake --help > /dev/null
    displayName: Test
